package Pod::ProjectDocs::ParserNew;

use strict;
use warnings;

use Pod::ProjectDocs::Parser::XHTML;

sub new {
    my $class = shift;
    my $self = {};
    bless $self, $class;
    return $self;
}

sub local_modules {
    my ($self, $modules) = @_;
    $self->{_local_modules} = $modules;
    return;
}

sub gen_html {
    my($self, %args) = @_;

    my $doc        = $args{doc};
    my $components = $args{components};
    my $mgr_desc   = $args{desc};
    #delete $self->{_source_code};
    my $charset = $doc->config->charset || 'UTF-8';

    my $parser = Pod::ProjectDocs::Parser::XHTML->new();
    $parser->html_charset('utf-8');
    $parser->html_header_tags($components->{css}->tag($doc));
    $parser->html_footer('<div class="footer">generated by <a href="http://search.cpan.org/perldoc?Pod::ProjectDocs"">Pod::ProjectDocs</a></div></body></html>');
    $parser->index(1);
    $parser->anchor_items(1);
    $parser->no_errata_section( 1 );
    #$self->perldoc_url_prefix( $self->perldoc_url_prefix );
    #$self->link_mappings( $self->link_mappings );

    #$self->current_files_output_path( $doc->get_output_path );
    #$self->_prepare($doc, $components, $mgr_desc);
    #   local $SIG{__WARN__} = sub { };

    open (my $fh, "<:encoding($charset)", $doc->origin) or warn $!;
    my $output;
    $parser->output_string(\$output);
    $parser->parse_file($fh);#
    #$self->parse_string_document('head1 NAME TEST');
    #close $fh;

    $doc->title($parser->title());
    #$self->current_files_output_path('');

    my $body_open_content = $self->_get_data($doc, $mgr_desc);
    $output =~ s/<body>/<body>$body_open_content/;

    return $output;
}

sub _get_data {
    my($self, $doc, $mgr_desc) = @_;
    my $tt = Pod::ProjectDocs::Template->new;
    my $text = $tt->process($doc, $doc->data, {
        title    => $doc->config->title,
        desc     => $doc->config->desc,
        name     => $doc->name,
        outroot  => $doc->config->outroot,
        src      => $doc->get_output_src_path,
        mgr_desc => $mgr_desc,
    });
    return $text if $^O ne 'MSWin32';

    while ( $text =~ s|href="(.*?)\\(.*?)"|href="$1/$2"| ) {
        next;
    }
    return $text;
}


1;
